site_name: AcessiCheck
repo_url: https://github.com/UnB-IHC/IHC_2025.2_Grupo01/
repo_name: IHC_2025.2_Grupo01

theme:
  name: material
  language: pt
  logo: assets/images/logo-icon.png
  favicon: assets/images/logo-icon.png
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

nav:
  - Introdução: index.md
  - Visão Geral: progresso.md
  - Design: design.md
  - Desenvolvimento Web: devweb.md
  - Conteúdo: conteudo.md
  - Gestão de Projetos: gestaodeprojetos.md
  - Heurísticas de Nielsen: heuristicas.md
  - Ferramentas de Acessibilidade: ferramentas.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js
  - js/main.js
  - js/summary.js

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - footnotes
