site_name: My Docs
theme:
  name: material

nav:
  - Home: index.md
  - Design: design.md
  - Desenvolvimento Web: devweb.md
  - Conteúdo: conteudo.md
  - Gestão de Projetos: gestaodeprojetos.md
  - Heurísticas de Nielsen: heuristicas.md
  - Ferramentas: ferramentas.md